services:
  - type: web
    name: vestigios-api
    env: node
    plan: free
    buildCommand: echo "skip" && true
    startCommand: node dist/index.js
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: CHANNEL_HANDLE
        value: "@VestigiosRPG"
